version: 2.1
jobs:
  build:
    docker:
      - image: alpine:3.7
    steps:
      - run:
          name: The First Step
          command: |
            echo 'É Verdade !!! Eles vem, quando o mundo vem 15/04/2021 -as 18H06!'
            echo 'This is the delivery pipeline'
